### ISSUE TITLE
Avaliação projeto Jables - template de módulo npm

### ISSUE THREAD

**Issue by vspedr** [training-center/code-review#11]
Oi pessoal,
Queria indicar meu repositório https://github.com/vspedr/jables para review. A ideia é ter um ponto de partida simples e adaptável para desenvolver um módulo para ser publicado no npm, levando em consideração que desejo usar ES6+ para desenvolver e que o código seja convertido em ES5 e minificado antes de ser publicado. Tem também algumas ferramentas adicionais como jest, husky e eslint, além de já estar configurado para rodar em integração contínua no Travis.

Sugestões de melhorias e boas práticas são bem vindas!

**Comment by luan0ap** [comment]
Issue meio antiga, mas gostaria de deixar minha colocação. Eu gostei do projeto, que é em suma um template, mas acho que a questão do lint deveria ser um pouco aberta pra quem for usar o template, eu particularmente prefiro o Standard do que o próprio lint. Mas ao todo curti bastante o projeto, até dei um fork pra usos futuros :v

**Comment by vspedr** [comment]
Valeu pelo feedback @luan0ap! Realmente o lint foi uma questão de preferência pessoal, mas a ideia geral era ter o mínimo necessário para iniciar um package mas que ainda seja simples o bastante para alterar conforme a preferência de quem utilizar :)

**Comment by edgarberlinck** [comment]
@vspedr Você acha que existe mais algum ponto a ser discutido? Se estive tudo ok peço para que fecha esta issue.
