### ISSUE TITLE
Avaliação de projeto random-quotes

### ISSUE THREAD

**Issue by samuelsilvadev** [training-center/code-review#12]
Eai pessoal fmz?

Gostaria de sugerir um repo que estou trabalhando para o freeCodeCamp [random-quote](https://github.com/samuelsilvadev/Random-quote-machine-freeCodeCamp) para review.

Nesse code é usado
 - JS vanilla
 - sass
 - gulp

O code já está fazendo o que é proposto, mas gostaria de dicas em que parte/partes poderiam melhorar.

Melhores práticas, Clean code, Patterns.. Qualquer sugestão, ajuda será super bem-vinda.

Desde já agradeço <3

**Comment by luan0ap** [comment]
Cara em Helper.js, arrow functions que retornam um valor nao precisa usar o parentêses nos parâmetros:

const $ = elm => document.querySelector(elm)

também  questão do ; então por questões de padronização, não se é recomendado usar o ; em aplicações JS, pois ao contrário de outras linguagens ele não é estritamente necessário.

Agora pode ser coisa minha, mas eu costumo separar por funções os callbacks do addEventListsner

**Comment by samuelsilvadev** [comment]
@luan0ap valeu mano pelas dicas mano, já vou fazer algumas alterações aqui.

Quanto aos ; eu costumo deixar pra evitar dores de cabeça, ja vi em processos de build bagunçar algumas coisas. E tbm gosto pra me lembrar que acabou a linha de código. 

> Agora pode ser coisa minha, mas eu costumo separar por funções os callbacks do addEventListsner

Você tem algum padrão que usa, tipo nome de functions dos listeners? Realmente acho que ficaria mais clean.

Super valeu pelas dicas mano

**Comment by luan0ap** [comment]
Padrao eu uso o standard para deixar mais organizado, agora para nomes normalmente tento deixar o mais especifico possível no nome da função o que ela irá fazer.
