### ISSUE TITLE
Avaliação do projeto MyReads - React

### ISSUE THREAD

**Issue by Lipemenezes** [training-center/code-review#13]
Oi pessoal, estou participando do programa de nanodegree em React na Udacity e estou fazendo o primeiro projeto.
A estrutura do projeto foi disponibilizada por eles, então não é necessário review de CSS por hora.
Se puderem dar uma olhada nos arquivos JS e lançarem umas dicas de onde melhorar o código, agradeço.

https://github.com/Lipemenezes/reactnd-project-myreads-starter

**Comment by carlosqsilva** [comment]
Dei uma olhada rápida  e percebi os seguintes pontos:
* Você poderia fazer uso de Functional Components em Book.js, Bookshelf.js e EmptyShelf.js ao invés de classes.
* Não entendi porque Bookshelf.js tem state, não há necessidade.
* Você poderia fazer mais uso de object spread.
* em Bookshelf.js você poderia fazer isso por exemplo:
```js
const Bookshelf = ({title, books, onShelfChange}) => (
 <div className="bookshelf">
        <h2 className="bookshelf-title">
          {title}
        </h2>
        <div className="bookshelf-books">
          <ol className="books-grid">
              {
                books.length ? 
                books.map(book => <Book book={book} key={book.id} onShelfChange={onShelfChange} /> ) : 
                <div>
                  <EmptyShelf message='No books here!' />
                </div>
              }
          </ol>
        </div>
      </div>
)
````

**Comment by vcapretz** [comment]
- coloque um `eslint` no projeto também pra ficar massa! em casos onde tem mais gente trabalhando ajuda muito! 
- as versões de pacotes em `dependencies` podem ser fixadas (remover o `^`), dessa forma vc garante que uma atualização de lib externa não passe a quebrar seu projeto 
- talvez o `App.js` pudesse estar um pouco mais abstraído, separa mais componentes e ai o App.js fica enxuto 

no geral tá ficando bom seu projeto! parabéns 🎉

**Comment by Lipemenezes** [comment]
Obrigado pelo feedback pessoal, assim que eu tiver um tempo vou ajustar essas coisas.
