### ISSUE TITLE
Avaliação do projeto - Clima Agora

### ISSUE THREAD

**Issue by danilogila** [training-center/code-review#14]
Boa tarde, pessoal! Fiz um site que utiliza uma API de clima e gostaria que vocês dessem uma avaliada principalmente no JavaScript.

Aqui está um link para acessar o site: http://climaagora.surge.sh/

Link para o repositório: https://github.com/danilogila/Clima-Agora

Abraços, Danilo Gila de Santana

**Comment by luan0ap** [comment]
Show mano, vamos lá alguns pontos que você poderia dar uma olhada.

- A questão das contantes como `key` seria interessante padronizar para letras maiúsculas como você fez para a `URL`

- Outro ponto também, seria interessante você separa a função `weatherId()` em um arquivo externo.

- E também, adotar o uso das `templates string`

- Agora talvez seja questão pessoal, mas eu costumo organizar as funções no topo e depois seto os evento, sei que funções não tem o esquema de hoisting mas é por organização mesmo.

- E também man, evite ao máximo usar `switch` no JS, procure usar funções e objetos. O mtmr0x tem um artigo bem interessante no Medium que fala sobre isso: [Substituindo condicionais por funções](https://medium.com/@mtmr0x/substituindo-condicionais-por-funções-e256fea57b9f)

Por enquanto é isso, tem mais alguns pontos que poderiam ser discutidos mas vou deixar esse mesmo que foram os que mais me chamaram a atenção. E por fim, parabéns pelo projeto man o/

**Comment by danilogila** [comment]
@luan0ap muito obrigado pelas dicas. Vou começar a aplicar as mudanças. A respeito do Switch não fazia ideia da performance ser menor.
