### ISSUE TITLE
E-commerce com NodeJS e MongoDB

### ISSUE THREAD

**Issue by wesleysantoss** [training-center/code-review#15]
Olá pessoal,
Gostaria de pedir avaliação desse repositório: [Link](https://github.com/wessleysanttos/ecommerce-estudos)
A ideia nele e treinar NodeJS e MongoDB.
Quem puder me passar um feedback do que pode ser melhorado eu ficarei muito grato. 😄

**Comment by jefersondaniel** [comment]
Parabéns pelo projeto, você está usando bem o EcmaScript e o Express, fiquei com pouca coisa pra comentar. Tem alguns pontos que podem ser melhorados:


### Gerenciamento de erros

Percebi que você tem alguns try catch nos controllers, isso poderia ser resolvido com middlewares.

### Configurações Hardcoded

Dentro da pasta config você tem versionado a porta HTTP que o servidor escuta e a url do mongose. Estas informações poderiam ser buscadas das variaveis de ambiente. Exemplo:

```js
mongoose.connect(process.env.MONGO_URI)
```

Então para rodar o comando você teria essas opções:

* Executar MONGO_URI=suauri node ./app.js
* Usar alguma lib que leia um arquivo .env, já usei "dotenv" (Nesse caso você colocaria o arquivo .env no .gitignore)
* Se você usar o docker a configuração do container já permite setar as variaveis de ambiente com mais facilidade.

### Design pattern Repository

Não sei você colocou o nome repositoryProduct por causa do design pattern, mas se for isso tem uma diferença entre o Repository e o Active Record. Um "document" do mongoose está mais próximo do ActiveRecord.


Seguem alguns links que podem ser interessantes para você

http://expressjs.com/pt-br/guide/error-handling.html
https://pt.stackoverflow.com/questions/25160/qual-a-diferen%C3%A7a-entre-os-design-patterns-data-mapper-e-active-record

**Comment by wesleysantoss** [comment]
Obrigado pelas orientações Jeferson.
Nos controller eu coloquei os try catch porque a função retorna uma promise, antes eu tratava esse tipo de situação com o .then e o .catch, mas colocando o try catch e usando o async await eu achei que o código ficou um pouco mais limpo, consegue me dar um exemplo de como eu trataria isso com um middleware?

Em relação a Configurações Hardcoded eu não conhecia essas soluções, vou pesquisar sobre e fazer uns testes.

Em relação ao Design pattern Repository eu coloquei aquele nome porque vi em um outro exemplo, eu não tenho total domínio de Design Pattern Repository e Active Record, vou pesquisar mais sobre esses assuntos. 

Mais uma vez, obrigado pelas orientações e pelos links, vou procurar estudar em cimas de suas orientações.

**Comment by jefersondaniel** [comment]
Eu vi agora que o express ainda não tem um suporte legal para promises. Uma forma de contornar isso e evitar repetição de código é criar uma função que envelope seu handler e faça o tratamento de erro.

```js
const asyncErrorHandler = fn => (req, res) => {
    fn(req, res).catch(e => {
        res.send({status: "Erro", mensagem: e})
    })
}

module.exports = {
    index: asyncErrorHandler(async (req, res) => {
        const produtos = await repositoryProduto.find()
        res.render('dashboard/index', {title: "Área de admin", produtos})
    })
}
```

**Comment by luan0ap** [comment]
Uma maneira interessante de tratar com os erros, é criar uma função e passar os erros para ela.

**Comment by wesleysantoss** [comment]
Ahhh entendi, Valeu Jeferson e Luan pelas dicas, vou estudar melhor essas partes.

**Comment by wesleysantoss** [comment]
Eu implementei essa função:
```
const asyncErrorHandler = fn => (req, res) => {
    fn(req, res).catch(e => {
        res.send({status: "Erro", mensagem: e})
    })
}
```

Ela funcionou perfeitamente, mas eu não consegui entender exatamente o porque funcionou D:
É uma função que recebe outra função e depois dentro dela (**fn(req, res).catch**) ela executa a função que recebeu?

**Comment by wesleysantoss** [comment]
Em cima da sugestões de vocês eu fiz algumas mudanças no código original.
Para meio que finalizar esse projetinho de estudo só vou montar um esquema de login, que seria simulando o login do responsável do e-commerce na área de adm.

Já pesquisei alguns materiais para implementar um login e já tenho em mente como fazer.
Mas caso vocês tenham algum material de estudo para isso com boas praticas e tudo mais, ficarei muito grato.

E desde já, muito obrigado pela ajuda pessoal.

**Comment by jefersondaniel** [comment]
A função asyncErrorHandler recebe a **função que você definiu** e retorna uma **nova função** para o router que contém a lógica de tratamento de erro.

Eu vi as alterações que você fez, ficou legal. Eu costumo fazer login enviando um token que vai ser usado no header Authorization das próximas requisições.

**Comment by wesleysantoss** [comment]
Entendi.
Ta certo, vou dar uma estudada nisso.
Valeu pela grande ajuda Jeferson. 
Abraços.

**Comment by edgarberlinck** [comment]
@wessleysanttos Você acha que o code review foi suficiente? Acha que mais alguma coisa pode ser acrescentada? Caso esteja tudo OK peço que feche esta issue.

**Comment by wesleysantoss** [comment]
Opa, foi suficiente sim. 
Muito obrigado pela ajuda de todos.
