### ISSUE TITLE
Avaliação Desafio Tagchatter - ReactJS

### ISSUE THREAD

**Issue by bartier** [training-center/code-review#17]
Olá pessoal,

Gostaria de indicar meu repositório para review. [Tagchatter](https://github.com/bartier/tagchatter-challenge).

O código já faz o que foi requisitado pelo desafio, porém gostaria de saber o que poderia melhorar (boas práticas)...

Muito obrigado desde já!

**Comment by edgarberlinck** [comment]
Oi amigo, abra um pull request para uma outra branch. Fica mais fácil para postar os comentários.

**Comment by edgarberlinck** [comment]
Vou colocar algumar considerações aqui:

**Button/index.js**

Este componente deve ser declarado como um componente burro (Presentational ou Dumb component). Você já fez isso no _ParrotsCounter_ e _SideBar_. : https://medium.com/@thejasonfile/dumb-components-and-smart-components-e7b33a698d43

**Header/index.js**
Mesma observação. 

**TagCharter.js**
Logo no construtor você tem um setInterval responsável por recarregar as mensagens. Acho legal um _clearInterval_ quando você destruir o componente (_componentWillUnmount_)

Mais interessante ainda seria se a responsabilidade de recarregar as mensagens fosse do componente _Messages_.

As chamadas as API poderiam estar em mais alto nível. Você poderia ter por exemplo: 
- No lugar de _api.get('/messages')_ prefira _api.listarMensagens()_ ou _api.listMessages()_
- Mesma coisa para os métodos: 
   - api.get("/messages/parrots-count")
   - api.post('/messages', newMessage), 
   - api.put(`/messages/${message.id}/unparrot`, {})
   - api.put(`/messages/${message.id}/parrot`, {})

**Comment by edgarberlinck** [comment]
Ah, um componente react possui um método chamado _componenetDidCatch_ que é muito útil para tratar exeptions.

**Comment by edgarberlinck** [comment]
Lembre-se de fechar esta issue quando estiver satisfeito com os reviews. Ok?

**Comment by bartier** [comment]
> Oi amigo, abra um pull request para uma outra branch. Fica mais fácil para postar os comentários.

[seria isso que você falou para fazer?](https://github.com/bartier/tagchatter-challenge/pull/1)

edit: vi que criou conflitos com esse PR...

**Comment by edgarberlinck** [comment]
Sim. Vou dar uma olhada na segunda feira.

**Comment by bartier** [comment]
@edgarberlinck obrigado!

**Comment by edgarberlinck** [comment]
@bartier As considerações feitas até o momento estão ok? Gostaria de mais alguma revisão ou já está satisfeito? Se sim, favor fechar esta issue.

**Comment by bartier** [comment]
@edgarberlinck As considerações estão ok sim, muito obrigado! Fecharei a issue.
