### ISSUE TITLE
Code Review aplicação Vuejs 2

### ISSUE THREAD

**Issue by mayronceccon** [training-center/code-review#2]
Olá pessoal!
Para estudo do Vuejs 2, criei um projeto de to-do list. Gostaria da revisão de vocês se algo pode ser melhorado, alguma regra foi quebrada, etc...

Segue o link do meu Github https://github.com/mayronceccon/todo-list-vuejs

**Comment by vinicius73** [comment]
1. Crie um arquivo responsável por configurar plugins e afins
https://github.com/mayronceccon/todo-list-vuejs/blob/master/src/main.js#L3-L8
```js
// main.js
import plugins from './plugins'

Vue.use(plugins)
```

```js
// plugins.js
import VueResource from 'vue-resource'
import VueMask from 'v-mask'
import { VueMaskDirective } from 'v-mask'

export default Vue => {
  Vue.directive('mask', VueMaskDirective)
  Vue.use(VueResource)
  Vue.use(VueMask)
}
```

**Comment by vinicius73** [comment]
2. tire proveito das novas features do JavaScrip como o [spread-operator](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Spread_operator)
https://github.com/mayronceccon/todo-list-vuejs/blob/master/src/App.vue#L105-L109
Encapsule as coisas em objetos para facilitar o entendimento do código e algumas tarefas

```js
this.tasks.push({ ...this.todoData })
```

**Comment by vinicius73** [comment]
3. isole e encapsule lógicas
https://github.com/mayronceccon/todo-list-vuejs/blob/master/src/App.vue#L111-L114

```js
methods: {
  saveTodos () {
    localStorage.setItem('tasks', JSON.stringify(this.tasks));
  }
}
```

**Comment by vinicius73** [comment]
4. Encasule seus componente, torne eles mais independentes.
https://github.com/mayronceccon/todo-list-vuejs/blob/master/src/App.vue#L9-L17
Use comunicação entre componentes, o estado do novo `todo` não precisa estar no componente pai.

```html
<TodoForm @save="addTodo" />
```

**Comment by vinicius73** [comment]
5. props entram / eventos saem
https://github.com/mayronceccon/todo-list-vuejs/blob/master/src/modules/todo-form.vue#L39-L86
Esta não foi uma abordagem feliz, evite ao **máximo** esse tipo de comunicação.

Como dito no [item 4](https://github.com/training-center/code-review/issues/2#issuecomment-325813038) o estado do todo novo não precisa estar no pai.

recomendação de leitura: [Estados com Vue.js — data, computed, props e store](https://blog.codecasts.com.br/estados-com-vue-js-data-computed-props-e-store-d8c6da4627ca)

**Comment by vinicius73** [comment]
6. considerações finais

Toda a visão de contemporização esta muito boa, a parte critica esta descrita no [item 5](https://github.com/training-center/code-review/issues/2#issuecomment-325813718)
Nos seus próximos estudos já pode partir para a [template webpack](https://github.com/vuejs-templates/webpack). Escolha uma opção de code style (eslint) e se acostume a manter um código uniforme. recomendo o [standardjs](https://standardjs.com), mas no geral esta é uma escolha pessoal, então esteja a vontade.

Tire mais proveito do ES2015+, há momentos que o código poderia estar mais expressivo se tivesse usado ele em sua totalidade.

No mais, parabéns e bons estudos.

**Comment by mayronceccon** [comment]
@vinicius73 Obrigado pelo feedback, fiz a refatoração seguindo as suas dicas! Obrigado!
