### ISSUE TITLE
Code Review aplicação usando React

### ISSUE THREAD

**Issue by brunorafael8** [training-center/code-review#3]
Opa pessoal :), 
Eu fiz um teste para uma vaga que era para fazer um app simples usando react (um dos meus primeiros projetos com react), eu gostaria que vocês me ajudassem apontando melhorias para esse teste que fiz e erros que cometi.

Segue o link do projeto: https://github.com/brunorafael8/React-Test

**Comment by alinebastos** [comment]
Coloca o link em algum canal do grupo, de repente ninguém viu aqui :)

**Comment by brunorafael8** [comment]
Eu ia apagar a issue, mas acabei fechando e abrindo ela

**Comment by brunorafael8** [comment]
Na verdade, acho que nem posso apagar

**Comment by rodrigooler** [comment]
@brunorafael8 abri algumas issues no teu repositório, dei watch para acompanhar a evolução.
