### ISSUE TITLE
Avaliação Secret of Mana - Website

### ISSUE THREAD

**Issue by danilogila** [training-center/code-review#5]
Há um tempinho atrás, encontrei um layout de um fan site de Secret of Mana no Dribbble. Como estou iniciando no mundo front end, resolvi tentar reproduzir o mesmo.  

Gostaria de opiniões a respeito do que posso melhorar no meu código e como deixar ele mais semântico possivel.

Repositório: https://github.com/danilogila/Secret-of-Mana
Link:  secretofmana.surge.sh

Abraços, e até mais o/

**Comment by akfzambrana** [comment]
Boa noite @danilogila 
vou fazer alguns comentários sobre teu código nas linhas abaixo sobre algumas coisas que acredito você pode melhorar :smile: 
O esquema vai ser assim, vou colocar um trecho de código e abaixo vou colocar o comentário a respeito e algumas referencias quando for necessário.

```html
<header>
	<a href="#"></a>
	<nav></nav>
</header>
```
Estas tags sem conteúdo nenhum são realmente necessárias? o ideal é que se não tiver conteúdo, elas não estejam ai. Não existe nenhuma "regra" que diga que um site precisa de `header` se efetivamente não tem um cabeçalho.

**Comment by akfzambrana** [comment]
```html
<a class="btn btn-about" href="#">About the Game</a>
<a class="btn btn-buy-home" href="#">Buy Now</a>
```
Uma observação neste caso para as classes `btn-about` e `btn-buy-home`. Imagina que você estivesse trabalhando em um site maior ou até em uma aplicação web, onde os botões fossem padronizados, neste caso você poderia mudar os nomes das tuas classes para que representassem por exemplo a importancia da ação ou do botão dentro da interface, por exemplo, "btn-acao-principal" ou "btn-destaque" ou "btn-primario", dessa forma, para quem for reutilizar eles, fica muito mais claro o que aquele botão representa dentro da identidade visual.
Imagina por exemplo que no futuro, a pessoa que trabalha no design, decide usar o mesmo padrão visual do botão "buy now" para um botão do cadastro de uma newsletter, nesse caso você teria que optar por exemplo entre:
- Repetir o css em outro lugar e isso seria um problema pois quando um mudasse tal vez o outro ficaria diferente
- Ter duas classes com o mesmo tipo visual mas com nomes diferentes para que elas sejam mais semanticas de acordo com o que os botões fazem
- Ter um botão com uma classe que não o representa

**Comment by akfzambrana** [comment]
```html
<img src="images/logo.png" alt="Secret of Mana">
```
O atributo `alt` das imagens, alem de ser uma ajuda caso a imagem não seja carregada, ele também é utilizado por leitores de tela para descrever a imagem. O ideal é que o texto do alt, não contenha apenas "o conteúdo" da imagem, mas também algo que ajude a pessoa com deficiencia visual a saber do que trata a imagem. Por exemplo você poderia colocar: "Logotipo do jogo Secret of Mana"

**Comment by akfzambrana** [comment]
```html
<div class="main-info">
<main class="main">
```
Em uma parte do código você tem uma div com a classe "main-info" e na proxima `section` você tem uma tag `main` com uma classe chamada "main". A tag `main` representa um conteúdo principal do `body` de um documento `html`, ou de uma porção de um documento ou aplicação http://devdocs.io/html/element/main. 
As duvidas são:
- Todas essas seções são realmente principais? 
- Se elas são principais, sera que a `div` com a classe "main" não deveria ser também uma tag `main`? 
- Sera que a tag "main" precisa mesmo de uma classe com o mesmo nome? sera que neste caso não seria bacana utilizar a tag para estilizar?
- Sera que essas tags `main` não poderiam ser apenas `div`? Pensando em que quando tudo é importante nada é importante :wink:

**Comment by akfzambrana** [comment]
```html
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
<br>
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
```
A tag `br` tem como objetivo quebrar um texto que irá continuar na linha de baixo como por exemplo na letra de uma música ou em um poema http://devdocs.io/html/element/br. 
A boa prática diz que não deve ser utilizado para dar um espaçamento entre dois textos, nesse caso o melhor seria utilizar a propriedade `margin` no CSS pois ẽ algo puramente visual.

**Comment by akfzambrana** [comment]
```html
<div class="characters-wrapper">
    <div class="characters-info randi">	
    </div>
    <p>Randi</p>
    <p class="class">Hero</p>
</div>
```
A foto de cada personagem é bem importante para o contexto dessa seção, sera que não seria melhor colocar uma tag `img` mesmo por questões de indexação e de acessibilidade?
Não acha que o nome do personagem poderia ser um título de importancia menor tipo um `h3`? 
A classe `class` se refere ao heroi ne? nesse caso já que você começou a utilizar BEM e classes com nomes compostos, sera que não faz mais sentido o nome dela ser `hero-class`?

**Comment by akfzambrana** [comment]
```html
<div class="zoom-wrapp">
    <div class="zoom-container">
        <a href="#"><i class="fa fa-eye" aria-hidden="true"></i></a>
    </div>
</div>
```
Neste pedaço você esta escondendo o ícone para os leitores de tela e isso é bacana, mas a pergunta que fica é como a pessoa que usa o leitor de tela vai saber o que esse link faz? não tem nenhum texto alternativo ou de ajuda
Uma outra observação, geralmente, se o `link` não leva para nenhum lugar, seja outra url/página ou seção do site, o ideal é que seja um `<button type="button">` que assim o leitor de tela irá saber que o botão executa uma ação, via JS ou não, e que não leva para nenhum outro lugar 
http://devdocs.io/html/element/button
https://davidwalsh.name/html5-buttons
https://css-tricks.com/use-button-element/

**Comment by akfzambrana** [comment]
```html
<h2>......Hero......</h2>
<h2>It is I who asked...the sword...</h2>
```
Ambos títulos fazem parte da mesma frase ne? Neste caso sera que não seria mais bacana usar um `<br>`?

**Comment by akfzambrana** [comment]
```html
<main class="txtalign">
```
Geralmente não é muito aconselhável colocar uma classe que tenha a ver com "layout" do elemento pois o layout pode mudar a qualquer momento e se fosse um site maior, com várias páginas ou até uma aplicação quando isso acontecesse ia ser bem chato de alterar em todos os htmls. O ideal é que as classes tenham a ver com o que o bloco/componente/conteudo representam e não com o layout que elas tem.

**Comment by akfzambrana** [comment]
De forma geral fica uma observação, o mais importante quando se desenvolve um projeto é ter consistencia e padrões. 
Por exemplo: 
- Se quiser utilizar classes com nomes compostos e quer utilizar `hifem` para juntar as palavras não tem problema, mas utilize em todos os lugares, o mesmo serve para o idioma utilizado e de preferencia os nomes de blocos, componentes, etc.
Não existe padrão perfeito ou "bom", existe apenas padrão. Geralmente se você trabalhar em um time o padrão será escolhido pelas pessoas do time em comum acordo ou de acordo de algum padrão específico. Se você esta trabalhando sozinho não tem problema, apenas analise qual padrão gosta mais e utilize ele de forma consistente.
Seguem algumas guias sobre padrões utilizados em alguns projetos
http://codeguide.co
http://workmanship.io
Ainda sobre padrões, o mesmo se aplica para o CSS, se vai utilizar tamanhos de fonte, espaçamentos, etc, escolha um tipo de unidade e daí utilize sempre ela, assim se tiver que trabalhar com responsividade vai ser muito mais facil a adaptação

**Comment by akfzambrana** [comment]
Indentar o código é uma boa prática para deixar o código mais bonito e legivel, além de ajudar a saber onde começam e onde terminam os componentes/blocos para futuras manutenções e até refações.
Geralmente as pessoas utilizam "espaços" em vez de "tabs" para identar pois fica mais consistente de um editor para outro, assim como geralmente se utiliza 2 ou 4 espaços

**Comment by akfzambrana** [comment]
```html
<head>
	<title>Secret of Mana</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
```
ah! sim, para ajudar na indexação do site, alem de melhorar a apresentação nos sites de busca, é bacana adicionar a tag `description` dentro da tag `head` :smile:

**Comment by akfzambrana** [comment]
Sobre a fonte `Helvetica`
A fonte helvética é uma fonte proprietária da [Linotype](https://www.fonts.com/font/linotype/helvetica/licenses) ou seja, ela é protegida por direitos autorais e tem licenças de uso muito específicas, geralmente não é permitido distribuir ela em um site sem autorização da Linotype e compra de uma licença de uso.
Existem muitas fontes que são livres e de ótima qualidade, você pode encontrar belissimas opções em sites como https://www.fontsquirrel.com/ ou https://fonts.google.com/

**Comment by akfzambrana** [comment]
![captura de tela de 2017-10-13 23-27-28](https://user-images.githubusercontent.com/400922/31571720-875b46ec-b06e-11e7-8bbc-0bb220459bd3.png)

Tem praticamente 1MB de peso em imagens, como o site tem imagens bonitas de background e tudo mais, não se esqueça de passar as imagens em algum otimizador para que possa reduzir o maximo de peso para que o teu site seja acessivel atravez de conexões mais lentas e que não "comam todo o plano de dados" quando acessado pelo 3g :wink: 

Uma outra coisa bacana para otimizar a performance sobre imagens é tentar ter a menor quantidade de requisições possiveis, para isso geralmente se faz um sprite de imagens pequenas para assim poder chamar uma imagem grande com imagens menores https://tableless.com.br/css-sprites/.

**Comment by akfzambrana** [comment]
```css
* {
  box-sizing: border-box;
  font-family: helvetica;
}
```
[O seletor asterisco é um dos mais caros](http://perfectionkills.com/profiling-css-for-fun-and-profit-optimization-notes/) em questão de performance de renderização para o CSS e deve ser utilizado com muito cuidado. 
Neste artigo a pessoa fala sobre algumas formas de fazer o reset do box-model e mostra uma das melhores tecnicas para fazer isso: https://css-tricks.com/box-sizing/

**Comment by akfzambrana** [comment]
```css
@font-face{
	font-family: 'helveticabold';
	src: url('../font/Helvetica/HelveticaNeue-Bold');
}
@font-face{
	font-family: 'helvetica';
	src: url('../font/Helvetica/HelveticaNeue-Light.otf');
}
```
Quando se trabalha com fontes diferentes das do sistema operacional é necessário se ater ao suporte mínimo de browser que você espera ter no site/aplicação https://css-tricks.com/snippets/css/using-font-face/
[Neste artigo](http://www.456bereastreet.com/archive/201012/font-face_tip_define_font-weight_and_font-style_to_keep_your_css_simple/) o autor mostra uma melhor forma de utilizar o font-face, depois dá uma lida pois estou utilizando essa forma na nova aplicação que estou desenvolvendo e que tem 6 tipos de fontes diferentes e esta sendo bem performatico e facil de usar :smile:

**Comment by akfzambrana** [comment]
Depois dá uma olhada nestes artigos, talvez eles possam ajudar a escolher um padrão para escrita do CSS e até para criação dos componentes e a reutilização dos estilos mais comuns

https://willianjusten.com.br/falando-sobre-rscss/
https://willianjusten.com.br/organizando-seu-css-com-itcss/
https://tableless.com.br/oocss-smacss-bem-dry-css-afinal-como-escrever-css/

Novamente deixo a dica de "escolhe um padrão e mantem ele em todo o projeto"

**Comment by akfzambrana** [comment]
Finalmente, espero ter ajudado de alguma forma.
O mais importante no "code review" é perceber que as observações, dúvidas, sugestões, críticas tem como objetivo apenas a melhoria do código e não tem nada a ver com a pessoa que escreveu. Submeter o código para review de alguem é algo que é um pouco desconfortável para quem está se submetendo à analise, mas que pode ser de grande benefício para todas as pessoas, tanto quem revisa quanto quem é revisado, pois atraves dos comentários pode-se chegar a um código com ótima qualidade e um grande aprendizado.

Caso tenha duvidas pergunte, não tem nada de errado em não saber algo ou até em não concordar com as observações feitas aqui.

Beijos da titia e um bom final de semana! :kissing_heart:

**Comment by danilogila** [comment]
Eu nem sei como te agradecer por esse feedback tão completo rsrs

De verdade, muito obrigado! Vou aplicar essas dicas nesse e em outros projetos que eu iria colocar aqui pra avaliação. Creio que com esses links que vc deixou, vou conseguir dar um level up nas minhas habilidades com CSS.

**Comment by alinebastos** [comment]
Melhor feedback! :green_heart:

**Comment by danilogila** [comment]
Depois de analisar o meu código, retirei muito lixo que havia nele. Realmente, muito obrigado pelo feedback. <3

**Comment by mikaelhadler** [comment]
Closed ? :)

**Comment by woliveiras** [comment]
Opa!
