### ISSUE TITLE
Avaliação projeto site Recanto Buffet

### ISSUE THREAD

**Issue by Guilherme-Chinaglia** [training-center/code-review#6]
Estou retomando meus estudos na área de Web, inclusive encontro-me inscrito no programa de mentoria aqui do CT. Enquanto aguardo ser chamado, estou colocando o que aprendi em meus estudos em alguns projetos. Como não tenho portfólio resolvi pegar alguns projetos de amigos e parentes sem custo nenhum para, além de construir este portfólio, aplicar os conhecimentos do estudo. 

Gostaria de receber **qualquer tipo de feedback para a melhoria deste meu projeto**, e **qualquer tipo de comentário** será muito bem recebido. Aguardo a ajuda do pessoal. Desde já obrigado, Abraço

Repositório: https://github.com/Guilherme-Chinaglia/recantobuffet
Repositório divertidalista: https://github.com/training-center/divertidalista/pull/14

**Comment by nicholasess** [comment]
#### HTML
Sempre ter em mente as metatags de redes sociais para gerar thumb, titulo, descrição para facilitar o compartilhamento.
https://github.com/Guilherme-Chinaglia/recantobuffet/blob/master/src/index.html#L6

#### JavaScript
O código poderia estar num arquivo .js e procure usar funções anônimas para não interferir em outros códigos https://github.com/Guilherme-Chinaglia/recantobuffet/blob/master/src/index.html#L253

#### Website
Adiciona o site numa gh-page para facilitar a visualização, pois não precisa baixar o repositório, rodar o gulp e etc.

Além disso, comece a estudar o Webpack, ele tem features boas que vão te ajudar no desenvolvimento, tanto quanto o gulp.

**Comment by Guilherme-Chinaglia** [comment]
Olá @nicholasess muito obrigado por sua ajuda e feedback!! Farei as alterações recomendadas. Obrigado mais uma vez!!
