### ISSUE TITLE
Avaliação: vspedr/movile-messaging

### ISSUE THREAD

**Issue by vspedr** [training-center/code-review#7]
Pessoal, adoraria que alguém de boa vontade pudesse fazer uma avaliação desse projeto:
https://github.com/vspedr/movile-messaging
É somente um wrapper em Node para a API de envio de SMS da Movile, que desenvolvi para utilizar em uma empresa que trabalhei e achei que pudesse ser útil para outros clientes Movile buscando uma forma de integração com serviços em Node.

Mais do que um review de código, queria sugestões para a questão dos testes: Como faz uso de uma API privada, que precisa de autenticação e tem custos associados ao seu uso, não sei qual seria uma boa maneira de montar uma suite de testes para o projeto. Gostaria ao menos de validar que os parâmetros passados para minhas funções formassem um request válido, mas sem realmente enviar esse request para a Movile. Alguma sugestão:

Outra questão é a dependência do `axios`, que parece ser um tanto pesada para um uso tão simples. Pensei em `node-fetch` ou o próprio `https` puro do node como alternativas, é válido?

**Comment by amadeu01** [comment]
@vspedr Olhei teu codigo. Achei bem legal! Acho que não tem muito que melhorar.
Talvez, só organizar o codigo em uma pasta `lib` ou `src`
Acho que não tem problema com o axios. Ficou bem simples usando ele. Se o cara que for usar tua lib, usar axios, fechou hahaha.

Quanto ao teste, eles não oferecem um sandbox? para teste? eu entrei no site deles. Mas, não olhei muito para procurar um sandbox. Se eles tiverem um sandbox, daí, acho que seria o ideial para fazer os teste.

Não consegui pensar em uma ideia muito boa para um teste :(

**Comment by vspedr** [comment]
Valeu pelo feedback! Acho que o jeito é entrar em contato com o pessoal de lá mesmo e ver se eles oferecem essa opção de sandbox, já tentei configurar um mock com o axios mas sem sucesso :/

**Comment by nicholasess** [comment]
@vspedr você pode criar um mock do server, simulando as requisições, assim você valida a entrada dos dados. Você pode usar o --coverage para o código, o jest mostra uma tabela listando os arquivos que precisam melhorar.

**Comment by amadeu01** [comment]
@nicholasess eu não tinha pensado em fazer um server mock. Tem como fazer isso tipo usando mocha ? e daí, fazer os request, e o mocha responde com algo que você já meio que escreveu? Mas, daí a lib não estaria salva para mudanças de resposta no servidor de produção, né?

Pois, quando faço um teste, tenho a intenção de que ele falhe caso alguém mude alguma parte do codigo que afeta o comportamento esperado daquele teste. Logo, a pessoa que implementou a nova funcionalidade, vai saber que "quebrou" um comportamento que existia.

Se faço teste de uma API, eu espero que ele quebre quando alguém altera a API. Mas, se eu mocko a resposta com algo fixo que eu quero, nunca vou saber que quebrou, sempre vai dar certo.

**Comment by nicholasess** [comment]
Não precisa de mocha se o estiver usando o jest, a intenção do mock é simular as respostas do server. O que o @vspedr fez, foi criar uma lib em cima de uma existente, então teoricamente ele sabe das respostas da api em produção. A intenção do mock, foi validar os parâmetros, o tipo deles e não necessariamente a api.

Um segundo raciocínio. Imagina que o vspedr fez uma lib que simbola o front end e está consumindo a api. É basicamente isso, ele vai validar o que está passando na api.

Quando trabalhamos somente com a api e o test nela, de fato você tem que validar as entradas e o código que está gerando o resultado

**Comment by amadeu01** [comment]
@nicholasess obrigado pela explicação.

Mas, minha dúvida era mais no sentido se a API muda de alguma forma, os testes não irão me mostrar que a api mudou.

**Comment by nicholasess** [comment]
@amadeu01 da pra validar se souber os parâmetros, ex:


O teste é ```..then((data) => expected(data).to.be.equal('ok'))```
v1 sempre retornou 'ok' -> passou, 
então a api muda e v2 retorna 'yes' -> vai quebrar

**Comment by amadeu01** [comment]
@nicholasess desculpa, não entendi

**Comment by vspedr** [comment]
Se entendi o raciocínio do @nicholasess, ele quis dizer que eu não preciso me preocupar em testar o retorno da API. Assumindo que caso eles façam uma breaking change na API vão indicar isso no número da versão, eu não preciso me preocupar pois minha lib está fixa na v1. Quando isso acontecer, eu também posso lançar uma nova versão da lib, que só trabalha com a nova API. No fim das contas, o foco dos testes aqui seria a lib (se faz o request certo) e não a API (se dá o retorno certo), isso é responsabilidade dos devs dela :) .

**Comment by nicholasess** [comment]
v1, v2 são as versões da api que você está testando.

Estamos testando o endpoint /user/1

v1 sempre retorna ```{message: 'ok'}```
```
it('test api v1', () => {
   api('/user/1').then((data) => expected(data.message).to.be.equal('ok'))
})

//O teste vai passar
```
Então a versão muda para v2 e agora retorna ```{message: 'yes'}```.
```
it('test api v1', () => {
   api('/user/1').then((data) => expected(data.message).to.be.equal('ok'))
})

//O teste vai quebrar
```

E agora?

**Comment by amadeu01** [comment]
@nicholasess valeu cara ! você é top!

**Comment by nicholasess** [comment]
Ufa hahaha

**Comment by amadeu01** [comment]
@nicholasess @vspedr fiz um pull request com os tests. Vi que o code climate reclamou um pouco. Mas, já dá para ter uma ideia 😄

**Comment by vspedr** [comment]
Valeu cara, vou dar uma olhada ASAP!

**Comment by nicholasess** [comment]
@amadeu01 cria um arquivo exportando dados que se repetem, assim você mantem o diretriz do DRY (don't repeat yourself)

**Comment by vspedr** [comment]
Agradeço o feedback, pessoal! Vou fechar a issue
