### ISSUE TITLE
Sugestão: criação de labels

### ISSUE THREAD

**Issue by rodolfo-mendes** [training-center/code-review#8]
Olá, sugiro criar alguns labels para ajudar a identificar o tipo e a linguagem dos projetos. Minhas sugestões:

- para identificar o tipo do projeto:
    - front-end
    - back-end
    - full-stack
- para identificar as linguagens/frameworks:
    - html
    - javascript
    - java 
    - php
    - angularjs
    - etc.

**Comment by woliveiras** [comment]
Valeu pela sugestão, @rodolfomendes 

Criamos as labels e estamos colocando nas issues. 

Obrigado pela colaboração.
