### ISSUE TITLE
Avaliação MovieRise - Website

### ISSUE THREAD

**Issue by danilogila** [training-center/code-review#9]
Gostaria de opiniões a respeito do que posso melhorar no meu código e como deixar ele mais semântico possível.

Repositório: https://github.com/danilogila/MovieRise
Link: http://teste-movierise.surge.sh/

Obrigado a quem puder ajudar rs

**Comment by FernandaBernardo** [comment]
Bom dia @danilogila 😊 

Vou tentar montar meu feedback aqui, qualquer dúvida estou à disposição e aberta também para ouvir, são apenas sugestões :)

- não existe um `<h1>` na sua página, e acredito que essa informação semanticamente é bem importante. Nesse caso, acho que poderia ser o logo
- Semanticamente falando, você aqui que o tipo do filme e a "|" seria um título? https://github.com/danilogila/MovieRise/blob/master/index.html#L40
- Essa `<div>` é necessária? https://github.com/danilogila/MovieRise/blob/master/index.html#L54
- Porque essas listas são uma `<ol>`? Ela é ordenada? A ordenação é obrigatória? https://github.com/danilogila/MovieRise/blob/master/index.html#L56, https://github.com/danilogila/MovieRise/blob/master/index.html#L1029, https://github.com/danilogila/MovieRise/blob/master/index.html#L1044
- Esses inputs/labels não poderiam ser `<button>`? https://github.com/danilogila/MovieRise/blob/master/index.html#L135
- Se essa `<div>` não tem conteúdo, ela não deveria ser colocada pelo JS? https://github.com/danilogila/MovieRise/blob/master/index.html#L151
- Precisa dessa `<div>`? A classe `copyright` não poderia estar na `<nav>` de dentro? https://github.com/danilogila/MovieRise/blob/master/index.html#L1042
- No mobile não aparecem os outros menus, só o que está selecionado
![image](https://user-images.githubusercontent.com/3588700/35096158-4343f2c8-fc32-11e7-8355-7cc04653a0e3.png)
- Cuidado ao colocar `<br>` porque estará SEMPRE quebrado. 
![image](https://user-images.githubusercontent.com/3588700/35096210-7ccb28b8-fc32-11e7-8121-8a087df805aa.png)

São algumas coisas, alguns detalhes, mas seu código está bom, parabéns!

**Comment by danilogila** [comment]
@FernandaBernardo Desculpe a demora em responder rs. Estou aplicando todas as melhorias que você apontou. Muito obrigado pelo feedback altamente construtivo.

Estou na luta pra virar um FrontEnd Jr e toda crítica é bem vinda rs

**Comment by FernandaBernardo** [comment]
@danilogila se quiser, quando terminar as melhorias, pode mandar novamente que posso olhar de novo 😊  Qualquer dúvida também que tiver, só pergunta ;D
